# Simple Theory About Pytorch
A simple guide to underestand pytorch

In [1]:
#imports
import torch
import numpy as np



| Dimensión | Nombre común | Ejemplo | Forma (shape) |
|-----------|--------------|---------|---------------|
| 0 | Escalar | `42` | `()` |
| 1 | Vector | `[1, 2, 3]` | `(3,)` |
| 2 | Matriz | `[[1,2],[3,4]]` | `(2,2)` |
| 3 | Tensor 3D | Imagen RGB | `(3, 480, 640)` |
| 4 | Tensor 4D | Batch de imágenes | `(32, 3, 480, 640)` |
| 5+ | Tensor ND | Secuencias de video | `(batch, frames, canales, alto, ancho)` |

contenedores de diferentes dimensiones:
- Escalar: una caja con un solo número
- Vector: un tubo con números en fila
- Matriz: una bandeja con filas y columnas
- Tensor 3D: un cubo de Rubik con números en cada celda
- Tensor 4D: varios cubos de Rubik apilados



In [ ]:
# create bidimensional tensor
tensor_bi = torch.zeros(3,5)
#tensor_bi = torch.ones(3,5)    # para crear un tensor con unos
print(tensor_bi)

# create a 2x3x4 tesor
tensor_tri = torch.rand(2,3,4)
print(tensor_tri)

# tensor desde una lista de datos
data = [[1,2,3], [4,5,6]]
converted = torch.tensor(data)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[[0.5737, 0.0192, 0.3646, 0.8841],
         [0.1085, 0.8075, 0.2313, 0.2993],
         [0.6165, 0.6315, 0.3672, 0.3738]],

        [[0.2244, 0.2344, 0.7598, 0.4755],
         [0.2596, 0.7592, 0.6950, 0.3737],
         [0.7961, 0.2104, 0.4430, 0.1107]]])


## Shape property
Es una propiedad que te dice las dimensiones de tu tensor

In [ ]:
# represetnacion de batch 32 imagenes RGB de 512x1024
data = torch.rand(32,3,512,1024)
print(f"Batch shape:",{data.shape})

Batch shape: {torch.Size([32, 3, 512, 1024])}


## Acceder a elementos
Funciona igual que en python

In [12]:
tensor = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Un elemento específico
print(tensor[0, 2])     # fila 0, columna 2 → 3
print(tensor[2, 1])     # fila 2, columna 1 → 8

# Una fila entera
print(tensor[1])        # [4, 5, 6]
print(tensor[1, :])     # [4, 5, 6] (equivalente)

# Una columna entera
print(tensor[:, 0])     # [1, 4, 7]

# Sub-matriz (slicing)
print(tensor[0:2, 1:3]) 
# [[2, 3],
#  [5, 6]]

tensor(3)
tensor(8)
tensor([4, 5, 6])
tensor([4, 5, 6])
tensor([1, 4, 7])
tensor([[2, 3],
        [5, 6]])


## Slicing sobre imagenes

In [ ]:
# Simulemos una imagen RGB de 480×640
imagen = torch.rand(3, 480, 640)  # [Canales, Alto, Ancho]

# Obtener solo el canal Rojo (índice 0)
canal_rojo = imagen[0, :, :]     # shape: (480, 640)
# o más elegante:
canal_rojo = imagen[0]           # shape: (480, 640)

# Recortar un parche central de 100×100
centro_h = 480 // 2
centro_w = 640 // 2
parche = imagen[:, centro_h-50:centro_h+50, centro_w-50:centro_w+50]
print(f"Parche shape: {parche.shape}")  # torch.Size([3, 100, 100])

# Obtener la primera fila de píxeles de cada canal
primera_fila = imagen[:, 0, :]  # shape: (3, 640)

## Operaciones Matematicas

In [ ]:
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

# Operaciones elemento a elemento
print(a + b)        # [5., 7., 9.]
print(a * b)        # [4., 10., 18.]  ← multiplicación elemento a elemento, NO producto punto
print(a ** 2)       # [1., 4., 9.]
print(torch.sqrt(a))  # [1., 1.4142, 1.7321]

# Funciones estadísticas
print(a.sum())      # 6.0
print(a.mean())     # 2.0
print(a.max())      # 3.0

# Operaciones sobre dimensiones específicas
matriz = torch.ones(4, 6)  # 4 filas, 6 columnas
# aplana o concatena filas o columnas
print(matriz.sum(dim=0))   # Suma cada columna → shape: (6,)
print(matriz.sum(dim=1))   # Suma cada fila    → shape: (4,)

tensor([5., 7., 9.])
tensor([ 4., 10., 18.])
tensor([1., 4., 9.])
tensor([1.0000, 1.4142, 1.7321])
tensor(6.)
tensor(2.)
tensor(3.)
tensor([4., 4., 4., 4., 4., 4.])
tensor([6., 6., 6., 6.])


## Cambiando la forma: .view() y .reshape()

In [ ]:
tensor = torch.arange(12)  # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
print(f"Original: {tensor.shape}")  # torch.Size([12])

# Reorganizar en matriz 3×4
matriz = tensor.view(3, 4)
print(matriz)
# tensor([[ 0,  1,  2,  3],
#         [ 4,  5,  6,  7],
#         [ 8,  9, 10, 11]])

# Reorganizar en tensor 3D: 2×2×3
t3d = tensor.view(2, 2, 3)
print(f"Shape 3D: {t3d.shape}")  # torch.Size([2, 2, 3])

# Aplanar de vuelta
aplanado = t3d.view(-1)  # -1 significa "calcula esta dimensión automáticamente"
print(f"Aplanado: {aplanado.shape}")  # torch.Size([12])

# Truco común en CNNs: aplanar manteniendo el batch
batch = torch.rand(16, 256, 7, 7)  # 16 imágenes, 256 canales, 7×7
batch_aplanado = batch.view(16, -1)  # 16, 256*7*7 = 16, 12544
print(f"Batch aplanado: {batch_aplanado.shape}")  # torch.Size([16, 12544])

## Broadcasting
Cuando operas tensores de diferente shape, PyTorch expande automáticamente el más pequeño:

In [16]:
# Sumar un escalar a un tensor → se suma a cada elemento
matriz = torch.ones(3, 4) * 10
matriz = matriz + 5
print(matriz)
# tensor([[15., 15., 15., 15.],
#         [15., 15., 15., 15.],
#         [15., 15., 15., 15.]])

# Sumar un vector a una matriz → se suma a cada fila
vector = torch.tensor([1.0, 2.0, 3.0, 4.0])
print(vector)
print(matriz + vector)  # shape: (3,4) + (4,) → el vector se "copia" en 3 filas
# tensor([[11., 12., 13., 14.],
#         [11., 12., 13., 14.],
#         [11., 12., 13., 14.]])

tensor([[15., 15., 15., 15.],
        [15., 15., 15., 15.],
        [15., 15., 15., 15.]])
tensor([1., 2., 3., 4.])
tensor([[16., 17., 18., 19.],
        [16., 17., 18., 19.],
        [16., 17., 18., 19.]])
